name: railway_navigation_app
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.6.3 # Text-to-Speech functionality
  speech_to_text: 7.0.0 # Voice Input functionality
  flutter_cube: 0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # Ensures Material Icons font is included
  uses-material-design: true

  # Adding assets to your project
  assets:
    - assets/welcome_background.jpg
    - assets/profile_background.jpg
    - assets/models/model.obj
    - assets/models/model.mtl
    - assets/models/texture.png
